version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-back-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-icy-mountain-aoc8bk69.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}
      APP_JWT_EXPIRATION_MS: 86400000
    restart: unless-stopped
    networks:
      - feed-back-network

networks:
  feed-back-network:
    driver: bridge
