spring.application.name=feed-back-server

# 1. Đã cập nhật đúng URL mới từ ảnh (Bỏ đuôi -pooler để kết nối trực tiếp, ổn định hơn với Hikari)
spring.datasource.url=jdbc:postgresql://ep-icy-mountain-aoc8bk69.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_he7myFrjx8bt

# 2. Cấu hình JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thằng này đã bị Hibernate báo DEPRECATION ở log trước, tốt nhất là XÓA HOẶC ẨN ĐI để Spring tự nhận diện.
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Bảo mật & JWT
app.jwt.secret=Thang@@Cho_Naocotin@!@!hdoccai...Naythi_@@bubuoiloN200123
app.jwt.expiration-ms=86400000